### PR TITLE
added main and gui stuff

### PR DESCRIPTION
**Pull request by chrismarrella**

### CODE REVIEW

**Review by AKovalyovv — CHANGES_REQUESTED** [review]
Abstract ViewModel was added, however GetRecipeViewModel does not extend it, which is something you should consider.

**Comment by AKovalyovv** [comment]
Also it does not make much sense to create the JFrame with the name "Get Recipe" on window creation. That should be done when we actually go into the "Get Recipe" use case.

**Comment by chrismarrella** [comment]
> Abstract ViewModel was added, however GetRecipeViewModel does not extend it, which is something you should consider.

in order for me to extend it I had to change firepropertychange to firepropertychangeD. I adjusted the code that calls on change_ instead of changed accordingly.

**Comment by chrismarrella** [comment]
> Also it does not make much sense to create the JFrame with the name "Get Recipe" on window creation. That should be done when we actually go into the "Get Recipe" use case.

was just a temp placeholder

**Comment by AKovalyovv** [comment]
Don't rename firePropertyChange to firePropertyChanged, as that's inconsistent with the method called on support.

**Comment by AKovalyovv** [comment]
Other than that, everything appears to be reasonable.

**Comment by chrismarrella** [comment]
> Don't rename firePropertyChange to firePropertyChanged, as that's inconsistent with the method called on support.

fixed

**Comment by AKovalyovv** [comment]
> > Don't rename firePropertyChange to firePropertyChanged, as that's inconsistent with the method called on support.
> 
> fixed

I am fairly sure you haven't pushed the changes.

**Comment by AKovalyovv** [comment]
Seems good.

**Pull request merged**
